export { ErrorPage } from './error/error'
export { default as ChatPage } from './chats/chats'
export { default as LoginPage } from './login/login'
export { default as RegistrationPage } from './registration/registration'
export { default as Profile } from './profile/profile'
export { NavigationPage } from './navigation/navigation'
export { PasswordChagePage } from './changePassword/changePassword'
